[project]
name = "gamepigeon-anagrams-bot"
version = "0.1.0"
description = "A bot that plays GamePigeon Anagrams using iPhone mirroring"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "easyocr>=1.7.2",
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
]
